### ISSUE TITLE
Depends?

### ISSUE THREAD

**Issue by zvezdochiot** [i-rinat/readdir-precache#1]
+Depends:
* https://github.com/troydhanson/uthash

**Comment by i-rinat** [comment]
Well, yeah, code uses uthash. And also utarray, utstring, and utlist. On Debian-based distros all of them are likely to be found in `uthash-dev` package.

Anyway, this is more like a publicly available source backup for own use than a user-friendly tool. It's a bit cumbersome to set up and use, and have some issues like too aggressive caching. It can be "fixed" by closing `mc` and starting it again, but it is hardly a user-friendly experience. The way it's implemented is inherently hacky.

**Comment by zvezdochiot** [comment]
overdue.
